An insurance company classifies its customers into 3 categories: below average, average, and above average. No one moves more than one state at a time.

For example, a customer cannot move from below average to above average or from above average to below average in a given period. After a given period, we notice that:

40% of those in the below average category become average
30% of those in the average category become above average
10% of those in the average category become below average
20% of those in the above average category are downgraded to average
Given the above:

Can you write the transition matrix for the model?
What is the limiting fraction of drivers in each of these categories? (e.g. find the steady state)

In [1]:
import numpy as np

In [2]:
m = np.array([ [.6,.4,0], [.1,.6,.3], [0,.2,.8] ])

In [3]:
m

array([[0.6, 0.4, 0. ],
       [0.1, 0.6, 0.3],
       [0. , 0.2, 0.8]])

In [12]:
dist = np.array([100, 100, 100])
for i in range(10):
    dist = np.dot(dist, m)
print(dist)

[ 28.31945504 109.85630112 161.82424384]


In [13]:
dist = np.array([100, 100, 100])
for i in range(100):
    dist = np.dot(dist, m)
print(dist)

[ 27.27272727 109.09090909 163.63636364]


In [14]:
dist = np.array([100, 100, 100])
for i in range(1000):
    dist = np.dot(dist, m)
print(dist)

[ 27.27272727 109.09090909 163.63636364]


In [15]:
dist = np.array([100, 100, 100])
for i in range(10000):
    dist = np.dot(dist, m)
print(dist)

[ 27.27272727 109.09090909 163.63636364]
